name: replica-comm-demo
region: nyc
services:
  - name: main-service
    github:
      repo: bikramkgupta/demo-replica-communication-app-platform
      branch: main
      deploy_on_push: true
    envs:
      - key: SERVICE_NAME
        value: main-service
      - key: REPLICA_COUNT
        value: "3"
      - key: PORT
        value: "8080"
    instance_size_slug: apps-s-1vcpu-1gb
    instance_count: 3
    http_port: 8080
    run_command: uvicorn main:app --host 0.0.0.0 --port 8080
    health_check:
      initial_delay_seconds: 15
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
      http_path: /health
